name: Create a Pull Request for a Release Branch

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        run: gh pr create --fill --draft --base live
        env:
          GITHUB_TOKEN: ${{github.token}}
