name: Python Pytest Testing

on:
  pull_request:
    branches:
      - develop
      - live

jobs:
  test:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest
