name: Python Pytest Testing

on:
  pull_request:
    branches:
      - develop
      - live

jobs:
  test:
    runs-on: ubuntu_latest
    steps:
      # checkout repo
      - uses: actions/checkout@v3

      # setup python\
      - name: Setup Python
        uses: actions/setup-python@v3

      # install requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # run pytest
      - name: Test with pytest
        run: pytest
